FROM apache/kafka:latest

USER root

ADD https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/1.0.1/jmx_prometheus_javaagent-1.0.1.jar /opt/jmx-exporter/jmx_prometheus_javaagent.jar

RUN chmod 644 /opt/jmx-exporter/jmx_prometheus_javaagent.jar

USER appuser
