services:
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_DB: loadtest_demo
  #     POSTGRES_USER: loadtest_demo
  #     POSTGRES_PASSWORD: loadtest_demo
  #   ports: ["5432:5432"]
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U loadtest_demo -d loadtest_demo"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 20

  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  prometheus:
    image: prom/prometheus:v2.55.0
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:11.3.1
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports: ["3000:3000"]
