### Simple endpoint
GET http://localhost:8080/

### Greeting with path variable
GET http://localhost:8080/greet/World

### Slow operation (500ms)
GET http://localhost:8080/slow

### Kafka - Send simple message
POST http://localhost:8080/kafka/send?message=Hello Kafka!!!!

### Kafka - Send message with key
POST http://localhost:8080/kafka/send-with-key?key=test-key&message=Hello with key!

### Kafka - Bulk send (100 messages, no delay)
POST http://localhost:8080/kafka/send-bulk?count=100&delayMs=0

### Kafka - Bulk send with delay (50 messages, 50ms delay)
POST http://localhost:8080/kafka/send-bulk?count=50&delayMs=50

### Kafka - Continuous send (30 seconds, 100ms interval = ~300 messages)
POST http://localhost:8080/kafka/send-continuous?durationSeconds=30&intervalMs=100

### Kafka - Continuous send (60 seconds, 50ms interval = ~1200 messages)
POST http://localhost:8080/kafka/send-continuous?durationSeconds=60&intervalMs=50

### Kafka - Send to multiple topics (20 messages total)
POST http://localhost:8080/kafka/send-topics?messagesPerTopic=5