server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loadtest_demo
    username: shhan
    password: shhan
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: loadtest_demo

app:
  seed:
    items: 100000
  cache:
    item-ttl-seconds: 60
