spring:
  application:
    name: kafka-consumer-demo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-consumer-demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.superhan.kafkaconsumerdemo: DEBUG
